"""Application-wide enumeration definitions.

All enums used across the ArchMind AI codebase are defined here and imported
from this single module. No other module defines its own copy of these values.

Dependency rule: this module imports only from Python stdlib.
"""

from __future__ import annotations

from enum import Enum, IntEnum


# ---------------------------------------------------------------------------
# Analysis quality enumerations
# ---------------------------------------------------------------------------


class Severity(IntEnum):
    """Severity levels for security findings and architecture weaknesses.

    Defined as IntEnum to support natural comparisons:
        Severity.CRITICAL > Severity.HIGH  # True
        max(findings, key=lambda f: f.severity)  # returns highest severity

    Assignment rule: severity is always assigned by the rule engine,
    never by LLM output.
    """

    CRITICAL = 5
    HIGH = 4
    MEDIUM = 3
    LOW = 2
    INFO = 1


class Priority(str, Enum):
    """Recommendation priority levels.

    Derivation rule:
    - P1: source finding has CRITICAL or HIGH severity.
    - P2: source finding has MEDIUM severity or significant architectural violation.
    - P3: LOW severity findings, quality improvements, non-blocking concerns.
    """

    P1 = "P1"
    P2 = "P2"
    P3 = "P3"


class Confidence(str, Enum):
    """Confidence levels for pattern detection and agent assessments.

    Signal basis:
    - HIGH:   Three or more independent corroborating signals.
    - MEDIUM: Two signals, or one strong signal.
    - LOW:    Single weak or ambiguous signal.

    LOW confidence findings must use qualified language in LLM narrative.
    """

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class EffortEstimate(str, Enum):
    """Rough effort estimate for implementing a recommendation.

    Generated by LLM with an explicit uncertainty qualifier in the prompt.
    Treat as directional guidance, not a precise estimate.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


# ---------------------------------------------------------------------------
# Architecture analysis enumerations
# ---------------------------------------------------------------------------


class ArchitecturePattern(str, Enum):
    """Detected software architecture patterns.

    Classification is produced by the Architecture Agent rule engine
    from signals in the ParsedCodeRepresentation.
    """

    LAYERED = "LAYERED"
    MVC = "MVC"
    HEXAGONAL = "HEXAGONAL"
    SERVICE_BASED = "SERVICE_BASED"
    MONOLITH_UNDIFFERENTIATED = "MONOLITH_UNDIFFERENTIATED"
    UNKNOWN = "UNKNOWN"


class PatternStrength(str, Enum):
    """Strength of evidence supporting a detected architecture pattern indicator."""

    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"


class CouplingType(str, Enum):
    """Classification of coupling problem type detected in a source file."""

    HIGH_FAN_IN = "HIGH_FAN_IN"
    """More modules import this file than the fan-in threshold allows."""

    HIGH_FAN_OUT = "HIGH_FAN_OUT"
    """This file imports more modules than the fan-out threshold allows."""

    BOTH = "BOTH"
    """Exceeds both fan-in and fan-out thresholds simultaneously."""


class SignalLevel(str, Enum):
    """Generic HIGH / MEDIUM / LOW level for cohesion and coupling assessments.

    Used for both CohesionAssessment (HIGH = good) and CouplingLevel
    (HIGH = bad). The semantic direction is determined by the field name
    and context, not by this enum itself.
    """

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class DefinitionKind(str, Enum):
    """Type of code definition extracted from a Tree-sitter AST node."""

    FUNCTION = "function"
    CLASS = "class"
    METHOD = "method"


# ---------------------------------------------------------------------------
# Security analysis enumerations
# ---------------------------------------------------------------------------


class OWASPCategory(str, Enum):
    """OWASP Top 10 2021 vulnerability categories.

    Used for mapping security findings to OWASP categories. NONE indicates
    a finding that does not map to any OWASP Top 10 category.
    """

    A01_BROKEN_ACCESS_CONTROL = "A01_BROKEN_ACCESS_CONTROL"
    A02_CRYPTOGRAPHIC_FAILURES = "A02_CRYPTOGRAPHIC_FAILURES"
    A03_INJECTION = "A03_INJECTION"
    A04_INSECURE_DESIGN = "A04_INSECURE_DESIGN"
    A05_SECURITY_MISCONFIGURATION = "A05_SECURITY_MISCONFIGURATION"
    A06_VULNERABLE_COMPONENTS = "A06_VULNERABLE_COMPONENTS"
    A07_AUTH_FAILURES = "A07_AUTH_FAILURES"
    A08_SOFTWARE_DATA_INTEGRITY = "A08_SOFTWARE_DATA_INTEGRITY"
    A09_LOGGING_MONITORING_FAILURES = "A09_LOGGING_MONITORING_FAILURES"
    A10_SSRF = "A10_SSRF"
    NONE = "NONE"


class SecretSignalType(str, Enum):
    """Types of hardcoded secret signals detectable via structural analysis."""

    PASSWORD_LITERAL = "password_literal"
    API_KEY_LITERAL = "api_key_literal"
    SECRET_LITERAL = "secret_literal"
    TOKEN_LITERAL = "token_literal"


class ValidationGapType(str, Enum):
    """Types of input/output validation gaps detectable via structural analysis."""

    MISSING_INPUT_VALIDATION = "missing_input_validation"
    MISSING_OUTPUT_ENCODING = "missing_output_encoding"
    MISSING_TYPE_CHECK = "missing_type_check"


class AuthSignalType(str, Enum):
    """Types of authentication-related risk signals detectable via structural analysis."""

    NO_GUARD_PRESENT = "no_guard_present"
    UNCONDITIONAL_ACCESS = "unconditional_access"
    BYPASSED_CHECK_INDICATOR = "bypassed_check_indicator"


class SQLSignalType(str, Enum):
    """Types of SQL injection risk signals detectable via structural analysis."""

    STRING_CONCATENATION_NEAR_DB_CALL = "string_concatenation_near_db_call"
    FORMAT_STRING_NEAR_DB_CALL = "format_string_near_db_call"


# ---------------------------------------------------------------------------
# Code quality enumerations
# ---------------------------------------------------------------------------


class TestCoverageSignal(str, Enum):
    """Test file presence signal derived from the test-to-total-file ratio.

    Thresholds are defined in config/constants.py:
    - ABSENT:  ratio < TEST_FILE_PRESENCE_THRESHOLD_PARTIAL
    - PARTIAL: TEST_FILE_PRESENCE_THRESHOLD_PARTIAL <= ratio < TEST_FILE_PRESENCE_THRESHOLD_PRESENT
    - PRESENT: ratio >= TEST_FILE_PRESENCE_THRESHOLD_PRESENT
    """

    PRESENT = "PRESENT"
    PARTIAL = "PARTIAL"
    ABSENT = "ABSENT"


class NamingConsistencySignal(str, Enum):
    """Naming convention consistency signal across the analysed codebase."""

    CONSISTENT = "CONSISTENT"
    INCONSISTENT = "INCONSISTENT"
    UNKNOWN = "UNKNOWN"


# ---------------------------------------------------------------------------
# RAG enumerations
# ---------------------------------------------------------------------------


class RAGDomain(str, Enum):
    """Knowledge base domain categories for RAG chunks.

    Values must match the keys in KB_CATEGORY_DOMAIN_MAP (config/constants.py).
    """

    ARCHITECTURE = "ARCHITECTURE"
    SECURITY = "SECURITY"
    QUALITY = "QUALITY"


# ---------------------------------------------------------------------------
# Recommendation enumerations
# ---------------------------------------------------------------------------


class RecommendationCategory(str, Enum):
    """Primary domain category of a generated recommendation."""

    ARCHITECTURE = "ARCHITECTURE"
    SECURITY = "SECURITY"
    QUALITY = "QUALITY"


# ---------------------------------------------------------------------------
# Dependency manifest enumerations
# ---------------------------------------------------------------------------


class ManifestType(str, Enum):
    """Supported dependency manifest file types."""

    PACKAGE_JSON = "package_json"
    REQUIREMENTS_TXT = "requirements_txt"
    GO_MOD = "go_mod"
    CARGO_TOML = "cargo_toml"
    POM_XML = "pom_xml"
    GEMFILE = "gemfile"
    PYPROJECT_TOML = "pyproject_toml"


# ---------------------------------------------------------------------------
# Job and workflow lifecycle enumerations
# ---------------------------------------------------------------------------


class JobStatus(str, Enum):
    """Persisted job lifecycle states stored in Supabase.

    Transitions:
        PENDING → RUNNING → COMPLETE
        PENDING → RUNNING → FAILED
        PENDING → FAILED  (validation failure before workflow start)

    COMPLETE and FAILED are terminal states. No further transitions allowed.
    """

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class WorkflowStatus(str, Enum):
    """In-memory LangGraph workflow execution states stored in AnalysisState.

    Transitions are strictly forward. No backward transitions are permitted.
    Fatal errors at any state transition to FAILED.
    """

    INITIALIZED = "INITIALIZED"
    INGESTING = "INGESTING"
    PARSING = "PARSING"
    ANALYZING_ARCHITECTURE = "ANALYZING_ARCHITECTURE"
    ANALYZING_SECURITY = "ANALYZING_SECURITY"
    RETRIEVING_RAG = "RETRIEVING_RAG"
    SYNTHESIZING = "SYNTHESIZING"
    ASSEMBLING = "ASSEMBLING"
    PERSISTING = "PERSISTING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class NodeExecutionStatus(str, Enum):
    """Execution status of an individual LangGraph node recorded in the audit log."""

    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


# ---------------------------------------------------------------------------
# Report enumerations
# ---------------------------------------------------------------------------


class SectionKey(str, Enum):
    """Report section identifiers in canonical display order.

    The integer order is enforced by the Report Assembly Service using
    SECTION_ORDER from config/constants.py. Consumer rendering depends
    on this sequence being stable across schema version 1.x.
    """

    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"
    REPOSITORY_OVERVIEW = "REPOSITORY_OVERVIEW"
    ARCHITECTURE_ASSESSMENT = "ARCHITECTURE_ASSESSMENT"
    SECURITY_FINDINGS = "SECURITY_FINDINGS"
    RECOMMENDATIONS = "RECOMMENDATIONS"
    ACTIONABLE_NEXT_STEPS = "ACTIONABLE_NEXT_STEPS"
