"""Data contracts for recommendation output and the final assembled report.

RecommendationSection is produced by the Recommendation Agent. FinalReport is
produced by the Report Assembly Service and persisted to Supabase.

Dependency rule: imports only from shared/types/enums, config/constants,
and stdlib/pydantic.
"""

from __future__ import annotations

import re
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field, field_serializer, field_validator, model_validator

from config.constants import (
    RECOMMENDATION_MAX_NEXT_STEPS,
    RECOMMENDATION_MIN_NEXT_STEPS,
    REPORT_SCHEMA_VERSION,
    SECTION_ORDER,
)
from shared.types.enums import (
    ArchitecturePattern,
    Confidence,
    EffortEstimate,
    Priority,
    RecommendationCategory,
    SectionKey,
    Severity,
)
from shared.types.analysis_types import GenerationMetadata


class Recommendation(BaseModel):
    """A single prioritised, RAG-grounded recommendation.

    Produced by the Recommendation Agent. Priority is assigned by the agent's
    rule engine based on the severity of source findings — not by the LLM.
    The LLM generates recommendation_text, rationale, and estimated_effort only.
    """

    recommendation_id: str = Field(
        ...,
        description=(
            "Scoped unique identifier within the RecommendationSection. "
            "Format: 'REC-NNN' where NNN is zero-padded to three digits (e.g. 'REC-001')."
        ),
    )
    priority: Priority = Field(
        ...,
        description=(
            "Priority assigned by the Recommendation Agent rule engine. "
            "P1 requires at least one CRITICAL or HIGH severity source finding."
        ),
    )
    title: str = Field(..., description="Short title for this recommendation.")
    category: RecommendationCategory = Field(
        ...,
        description="Primary domain of this recommendation.",
    )
    source_finding_ids: list[str] = Field(
        ...,
        min_length=1,
        description=(
            "Finding or weakness IDs from ArchitectureSection or SecuritySection "
            "that this recommendation addresses (e.g. ['AW-001', 'SF-002']). "
            "At least one source finding is required."
        ),
    )
    rag_chunk_ids_used: list[str] = Field(
        default_factory=list,
        description=(
            "chunk_id values from RAGContext.retrieved_chunks that informed "
            "this recommendation."
        ),
    )
    context: str = Field(
        ...,
        min_length=10,
        description=(
            "Synthesised knowledge base context from the referenced RAG chunks. "
            "Generated by the LLM from chunk content — not raw chunk text."
        ),
    )
    recommendation_text: str = Field(
        ...,
        min_length=30,
        description=(
            "LLM-generated recommendation. Must be specific and actionable. "
            "Must not prescribe exact code solutions."
        ),
    )
    rationale: str = Field(
        ...,
        min_length=20,
        description="LLM-generated explanation of why this issue matters and the risk if ignored.",
    )
    estimated_effort: EffortEstimate = Field(
        ...,
        description=(
            "Rough effort estimate generated by LLM. Prompt engineering ensures "
            "an explicit uncertainty qualifier accompanies this estimate."
        ),
    )

    @field_validator("recommendation_id", mode="before")
    @classmethod
    def validate_recommendation_id_format(cls, value: str) -> str:
        """Enforce the REC-NNN scoped identifier format."""
        if not re.match(r"^REC-\d{3}$", str(value)):
            raise ValueError(
                f"recommendation_id '{value}' does not match required format 'REC-NNN' "
                "(e.g. 'REC-001')."
            )
        return value


class RecommendationSection(BaseModel):
    """Complete output of the Recommendation Agent for a single analysis job.

    Synthesises findings from ArchitectureSection and SecuritySection with
    RAG-retrieved knowledge base context into prioritised, actionable output.

    Ownership rules:
    - Recommendation Agent creates and fully populates this contract.
    - Recommendations are ordered: all P1 first, then P2, then P3.
    - Priority assignment is rule-based; LLM generates text fields only.
    - Not persisted to Supabase independently; embedded in FinalReport.
    """

    section_id: UUID = Field(..., description="Unique identifier for this section instance.")
    job_id: UUID = Field(..., description="Parent analysis job.")
    executive_summary: str = Field(
        ...,
        min_length=100,
        description=(
            "LLM-generated synthesis of overall codebase health and most critical concerns. "
            "Minimum 100 characters."
        ),
    )
    recommendations: list[Recommendation] = Field(
        default_factory=list,
        description=(
            "Prioritised recommendations ordered P1 → P2 → P3. "
            "At least one recommendation is required when source_finding_count > 0."
        ),
    )
    actionable_next_steps: list[str] = Field(
        ...,
        description=(
            f"Ordered list of concrete next steps (most urgent first). "
            f"Min {RECOMMENDATION_MIN_NEXT_STEPS}, "
            f"Max {RECOMMENDATION_MAX_NEXT_STEPS} items."
        ),
    )
    recommendation_counts_by_priority: dict[str, int] = Field(
        ...,
        description=(
            "Count of recommendations per priority level, keyed by Priority enum value "
            "(e.g. {'P1': 2, 'P2': 3, 'P3': 1})."
        ),
    )
    generated_at: datetime = Field(
        ..., description="UTC timestamp when the Recommendation Agent completed generation."
    )
    generation_metadata: GenerationMetadata = Field(
        ..., description="Gemini API call metadata for this generation."
    )
    source_finding_count: int = Field(
        ...,
        ge=0,
        description=(
            "Total count of findings from ArchitectureSection and SecuritySection "
            "that informed this recommendation output."
        ),
    )
    rag_chunks_used_count: int = Field(
        ...,
        ge=0,
        description="Total count of RAG chunks incorporated across all recommendations.",
    )
    no_significant_findings_note: str | None = Field(
        default=None,
        description=(
            "Explanatory note when source_finding_count is zero. "
            "None when findings exist."
        ),
    )

    @model_validator(mode="after")
    def validate_next_steps_count(self) -> "RecommendationSection":
        """Enforce min/max bounds on actionable_next_steps."""
        count = len(self.actionable_next_steps)
        if count < RECOMMENDATION_MIN_NEXT_STEPS:
            raise ValueError(
                f"actionable_next_steps must contain at least "
                f"{RECOMMENDATION_MIN_NEXT_STEPS} items. Got {count}."
            )
        if count > RECOMMENDATION_MAX_NEXT_STEPS:
            raise ValueError(
                f"actionable_next_steps must not exceed "
                f"{RECOMMENDATION_MAX_NEXT_STEPS} items. Got {count}."
            )
        return self

    @model_validator(mode="after")
    def validate_recommendations_ordered_by_priority(self) -> "RecommendationSection":
        """Enforce that recommendations are ordered P1 → P2 → P3."""
        priority_order = {Priority.P1: 1, Priority.P2: 2, Priority.P3: 3}
        for i in range(1, len(self.recommendations)):
            prev = priority_order[self.recommendations[i - 1].priority]
            curr = priority_order[self.recommendations[i].priority]
            if curr < prev:
                raise ValueError(
                    f"recommendations must be ordered P1 → P2 → P3. "
                    f"Found {self.recommendations[i].priority.value} after "
                    f"{self.recommendations[i - 1].priority.value} at index {i}."
                )
        return self

    @model_validator(mode="after")
    def validate_recommendation_ids_unique(self) -> "RecommendationSection":
        """Enforce uniqueness of recommendation_id values."""
        ids = [r.recommendation_id for r in self.recommendations]
        if len(ids) != len(set(ids)):
            duplicates = [rid for rid in ids if ids.count(rid) > 1]
            raise ValueError(
                f"Duplicate recommendation_id values detected: {duplicates}"
            )
        return self

    @model_validator(mode="after")
    def validate_priority_counts_consistent(self) -> "RecommendationSection":
        """Enforce that recommendation_counts_by_priority matches the actual list."""
        actual: dict[str, int] = {p.value: 0 for p in Priority}
        for rec in self.recommendations:
            actual[rec.priority.value] += 1
        for priority_val, expected_count in actual.items():
            declared = self.recommendation_counts_by_priority.get(priority_val, 0)
            if declared != expected_count:
                raise ValueError(
                    f"recommendation_counts_by_priority['{priority_val}'] is {declared} "
                    f"but the recommendations list contains {expected_count} {priority_val} items."
                )
        return self

    @model_validator(mode="after")
    def validate_no_findings_note_when_empty(self) -> "RecommendationSection":
        """Enforce that no_significant_findings_note is set when there are no source findings."""
        if self.source_finding_count == 0 and self.no_significant_findings_note is None:
            raise ValueError(
                "no_significant_findings_note must be provided when source_finding_count is 0."
            )
        if self.source_finding_count > 0 and self.no_significant_findings_note is not None:
            raise ValueError(
                "no_significant_findings_note must be None when source_finding_count > 0."
            )
        return self


# ---------------------------------------------------------------------------
# Final report types
# ---------------------------------------------------------------------------


class ReportSection(BaseModel):
    """A single ordered section within the final assembled report."""

    section_order: int = Field(
        ...,
        ge=1,
        description="Position in the report (1-indexed). Canonical order from SECTION_ORDER.",
    )
    section_key: SectionKey = Field(
        ..., description="Section identifier. Unique within a FinalReport."
    )
    section_title: str = Field(..., description="Display title for this section.")
    content_markdown: str = Field(
        ...,
        description="Markdown content for this section only.",
    )


class ReportMetadata(BaseModel):
    """Structured summary of key signals extracted from report content.

    Enables lightweight querying of report signals without parsing markdown.
    Persisted alongside the full markdown in Supabase.
    """

    primary_language: str = Field(
        ..., description="Primary programming language detected in the repository."
    )
    detected_architecture_pattern: ArchitecturePattern = Field(
        ..., description="Architecture pattern classified by the Architecture Agent."
    )
    architecture_confidence: Confidence = Field(
        ..., description="Confidence level of the architecture pattern classification."
    )
    security_finding_count: int = Field(
        ..., ge=0, description="Total number of security findings in the report."
    )
    finding_counts_by_severity: dict[str, int] = Field(
        ...,
        description="Security finding count per severity level, keyed by Severity enum name.",
    )
    highest_severity_finding: Severity | None = Field(
        default=None,
        description="Highest severity level present in security findings. None when no findings.",
    )
    recommendation_count: int = Field(
        ..., ge=0, description="Total number of recommendations in the report."
    )
    p1_recommendation_count: int = Field(
        ..., ge=0, description="Count of P1 (immediate action) recommendations."
    )
    rag_chunks_used_count: int = Field(
        ..., ge=0, description="Total RAG chunks incorporated across all recommendations."
    )
    analysis_duration_seconds: int = Field(
        ..., ge=1, description="Total elapsed time from job start to report completion in seconds."
    )
    total_files_analyzed: int = Field(
        ..., ge=0, description="Total files successfully parsed during the analysis."
    )
    total_llm_tokens_used: int = Field(
        ..., ge=0, description="Aggregate token count (input + output) across all LLM calls."
    )

    @field_serializer("highest_severity_finding")
    def serialize_severity(self, value: "Severity | None") -> str | None:
        return value.name if value is not None else None


class FinalReport(BaseModel):
    """The complete assembled analysis report persisted to Supabase.

    Produced by the Report Assembly Service and written to Supabase by the
    Persistence Node. This is the terminal artifact of the entire workflow.

    Immutability rule:
    - FinalReport is immutable after persistence.
    - Re-analysis creates a new FinalReport with a new report_id.
    - The API Gateway reads FinalReport but never modifies it.

    Section ordering:
    - sections must contain exactly 6 entries covering all SectionKey values.
    - section_order values must be 1–6 matching SECTION_ORDER from config/constants.py.
    """

    report_id: UUID = Field(..., description="Unique identifier for this report.")
    job_id: UUID = Field(..., description="Parent analysis job. Foreign key to JobRecord.")
    repo_url: str = Field(..., description="Repository URL that was analysed.")
    repo_name: str = Field(..., description="Repository name extracted from the URL.")
    generated_at: datetime = Field(
        ..., description="UTC timestamp when report assembly completed."
    )
    schema_version: str = Field(
        default=REPORT_SCHEMA_VERSION,
        description=(
            f"Contract schema version. MVP value: '{REPORT_SCHEMA_VERSION}'. "
            "Incremented on breaking changes."
        ),
    )
    markdown_content: str = Field(
        ...,
        min_length=1,
        description="Complete assembled report as a single markdown string.",
    )
    metadata: ReportMetadata = Field(
        ...,
        description="Structured key signals for lightweight querying without parsing markdown.",
    )
    sections: list[ReportSection] = Field(
        ...,
        description=(
            "Ordered section records. Must contain exactly 6 entries covering "
            "all SectionKey values in canonical order."
        ),
    )

    @field_validator("schema_version", mode="before")
    @classmethod
    def validate_schema_version(cls, value: str) -> str:
        """Enforce that schema_version matches the current contract version."""
        if str(value) != REPORT_SCHEMA_VERSION:
            raise ValueError(
                f"schema_version must be '{REPORT_SCHEMA_VERSION}'. Got '{value}'."
            )
        return value

    @model_validator(mode="after")
    def validate_sections_complete_and_ordered(self) -> "FinalReport":
        """Enforce exactly 6 sections covering all SectionKey values in canonical order."""
        expected_keys = [SectionKey(key) for key in SECTION_ORDER]

        if len(self.sections) != len(expected_keys):
            raise ValueError(
                f"FinalReport must contain exactly {len(expected_keys)} sections. "
                f"Got {len(self.sections)}."
            )

        for i, (section, expected_key) in enumerate(zip(self.sections, expected_keys), start=1):
            if section.section_order != i:
                raise ValueError(
                    f"Section at position {i} has section_order={section.section_order}. "
                    f"Expected {i}."
                )
            if section.section_key != expected_key:
                raise ValueError(
                    f"Section at position {i} has section_key='{section.section_key.value}'. "
                    f"Expected '{expected_key.value}'."
                )
        return self

    @model_validator(mode="after")
    def validate_p1_count_le_total(self) -> "FinalReport":
        """Enforce that p1_recommendation_count does not exceed recommendation_count."""
        meta = self.metadata
        if meta.p1_recommendation_count > meta.recommendation_count:
            raise ValueError(
                f"p1_recommendation_count ({meta.p1_recommendation_count}) cannot exceed "
                f"recommendation_count ({meta.recommendation_count})."
            )
        return self
